### ISSUE TITLE
Seafile Container crash immediately

### ISSUE THREAD

**Issue by kort3z** [haiwen/seafile-docker#160]
Hi there, 

I have a issue with the last version of Seafile. 

When I start the docker-compose file, seafile is crashing instantly. 

``` seafile-mysql | 2019-07-02 18:08:30 139841452623872 [Note] mysqld (mysqld 10.1.40-MariaDB-1~bionic) starting as process 1 ...
seafile-mysql | 2019-07-02 18:08:31 139841452623872 [Note] InnoDB: Using mutexes to ref count buffer pool pages
seafile      | *** Running /etc/my_init.d/01_create_data_links.sh...
seafile-mysql | 2019-07-02 18:08:31 139841452623872 [Note] InnoDB: The InnoDB memory heap is disabled
seafile      | invalid time zone
seafile-mysql | 2019-07-02 18:08:31 139841452623872 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
seafile      | *** /etc/my_init.d/01_create_data_links.sh failed with status 1
seafile      |
seafile-mysql | 2019-07-02 18:08:31 139841452623872 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
seafile      | *** Killing all processes...
seafile-mysql | 2019-07-02 18:08:31 139841452623872 [Note] InnoDB: Compressed tables use zlib 1.2.11
seafile-mysql | 2019-07-02 18:08:31 139841452623872 [Note] InnoDB: Using Linux native AIO
seafile-mysql | 2019-07-02 18:08:31 139841452623872 [Note] InnoDB: Using SSE crc32 instructions
seafile-mysql | 2019-07-02 18:08:31 139841452623872 [Note] InnoDB: Initializing buffer pool, size = 256.0M
seafile-mysql | 2019-07-02 18:08:31 139841452623872 [Note] InnoDB: Completed initialization of buffer pool
seafile-mysql | 2019-07-02 18:08:31 139841452623872 [Note] InnoDB: Highest supported file format is Barracuda.
seafile-mysql | 2019-07-02 18:08:31 139841452623872 [Note] InnoDB: 128 rollback segment(s) are active.
seafile-mysql | 2019-07-02 18:08:31 139841452623872 [Note] InnoDB: Waiting for purge to start
seafile-mysql | 2019-07-02 18:08:31 139841452623872 [Note] InnoDB:  Percona XtraDB (http://www.percona.com) 5.6.43-84.3 started; log sequence number 1616837
seafile-mysql | 2019-07-02 18:08:31 139840490305280 [Note] InnoDB: Dumping buffer pool(s) not yet started
seafile-mysql | 2019-07-02 18:08:31 139841452623872 [Note] Plugin 'FEEDBACK' is disabled.
seafile-mysql | 2019-07-02 18:08:31 139841452623872 [Note] Server socket created on IP: '::'.
seafile-mysql | 2019-07-02 18:08:31 139841452623872 [Warning] 'proxies_priv' entry '@% root@6f2947f77abb' ignored in --skip-name-resolve mode.
seafile-mysql | 2019-07-02 18:08:31 139841452623872 [Note] mysqld: ready for connections.
seafile-mysql | Version: '10.1.40-MariaDB-1~bionic'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
seafile exited with code 1
``` 

It seems to be related to the timezone, unfortunately none of my changes worked. Here is my docker-compose file.
Note, however, that with our without USE-TZ, nothing change.

``` 
version: '2.0'
services:
  db:
    image: mariadb:10.1
    container_name: seafile-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pass  # Requested, set the root's password of MySQL service.
      - MYSQL_LOG_CONSOLE=true
    volumes:
      - /home/ubuntu/seafile-mysql/db:/var/lib/mysql  # Requested, specifies the path to MySQL data persistent store.
    networks:
      - seafile-net

  memcached:
    image: memcached:1.5.6
    container_name: seafile-memcached
    entrypoint: memcached -m 256
    networks:
      - seafile-net
          
  seafile:
    image: seafileltd/seafile-mc:latest
    container_name: seafile
    ports:
      - "80:80"
#     - "443:443"  # If https is enabled, cancel the comment.
    volumes:
      - /home/ubuntu/seafile-data:/shared   # Requested, specifies the path to Seafile data persistent store.
    environment:
      - DB_HOST=db
      - DB_ROOT_PASSWD=pass  # Requested, the value shuold be root's password of MySQL service.
      - USE_TZ=True
      - TIME_ZONE=Etc/UTC  # Optional, default is UTC. Should be uncomment and set to your local time zone.
      - SEAFILE_ADMIN_EMAIL=me@mymail.com # Specifies Seafile admin user, default is 'me@example.com'.
      - SEAFILE_ADMIN_PASSWORD=pass     # Specifies Seafile admin password, default is 'asecret'.
      - SEAFILE_SERVER_LETSENCRYPT=false   # Whether to use https or not.
      - SEAFILE_SERVER_HOSTNAME=seafile.idruide.cloud # Specifies your host name if https is enabled.
    depends_on:
      - db
      - memcached
    networks:
      - seafile-net

networks:
  seafile-net:
``` 

If anyone has an idea, I can't go ahead to give a demonstration to the IT team to switch to Seafile Pro.
