### ISSUE TITLE
Custom memcached service name

### ISSUE THREAD

**Issue by CS-Tao** [haiwen/seafile-docker#196]
The same issue is #169. But I don't think the solution https://github.com/haiwen/seafile-docker/issues/169#issuecomment-524792259 is reasonable.

Custom `memcached` service name by environment :
```yml
version: '2.0'
services:
  seafile-db:
    image: mariadb:10.1
  ...

  seafile-memcached:
    image: memcached:1.5.6
  ...

  seafile:
    image: seafileltd/seafileenvi-mc:latest
    environment:
      - DB_HOST=seafile-db
      - MEM_HOST=seafile-memcached
  ...
```
