### ISSUE TITLE
Internal Server Error after upgrading from 9 to 10

### ISSUE THREAD

**Issue by FluffyDiscord** [haiwen/seafile-docker#340]
I tried to move from v9 to v10. The upgrade script went fine after pulling the new docker image AFAIK. The webinterface is dead, throwing Internal Server Error message. I have not changed any configuration, except the required steps from here https://manual.seafile.com/upgrade/upgrade_notes_for_10.0.x/ and here https://manual.seafile.com/docker/upgrade/upgrade_docker/#upgrade-from-90-to-100

Attaching also docker compose up log, if that helps in any way [docker-compose-up.log](https://github.com/haiwen/seafile-docker/files/11642609/docker-compose-up.log)

Am I missing something?

docker-compose.yml
```yaml
version: '2.0'
services:
  db:
    image: mariadb:10.6
    container_name: seafile-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=db_dev  # Requested, set the root's password of MySQL service.
      - MYSQL_LOG_CONSOLE=true
    volumes:
      - /mnt/user0/appdata-array/seafile/db:/var/lib/mysql  # Requested, specifies the path to MySQL data persistent store.
    networks:
      - seafile-net

  memcached:
    image: memcached:1.6.18
    container_name: seafile-memcached
    entrypoint: memcached -m 256
    networks:
      - seafile-net

  elasticsearch:
    image: elasticsearch:8.5.3
    container_name: seafile-elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g
    volumes:
      - /mnt/user0/appdata-array/seafile/es:/usr/share/elasticsearch/data  # Requested, specifies the path to Elasticsearch data persistent store.
    networks:
      - seafile-net

  seafile:
    image: docker.seadrive.org/seafileltd/seafile-pro-mc:latest
    container_name: seafile
    ports:
      - "8085:80"
      # - "443:443"  # If https is enabled, cancel the comment.
    volumes:
      - /mnt/user0/appdata-array/seafile/data:/shared   # Requested, specifies the path to Seafile data persistent store.
    environment:
      - DB_HOST=db
      - DB_ROOT_PASSWD=db_dev  # Requested, the value shuold be root's password of MySQL service.
      #      - TIME_ZONE=Asia/Shanghai # Optional, default is UTC. Should be uncomment and set to your local time zone.
      - SEAFILE_ADMIN_EMAIL=email@email.com # Specifies Seafile admin user, default is 'me@example.com'
      - SEAFILE_ADMIN_PASSWORD=password     # Specifies Seafile admin password, default is 'asecret'
      - SEAFILE_SERVER_LETSENCRYPT=false   # Whether to use https or not
      - SEAFILE_SERVER_HOSTNAME=hostname.com # Specifies your host name if https is enabled
    depends_on:
      - db
      - memcached
      - elasticsearch
    networks:
      - seafile-net

networks:
  seafile-net:
```
