### ISSUE TITLE
Problem with  docker-compose

### ISSUE THREAD

**Issue by dakky** [haiwen/seafile-docker#53]
Hello. I'm trying to run seafile-docker via docker compose. 
my docker-compose file looks like that:

```
version: '3'

services:
  seafile:
    image: seafileltd/seafile:6.2.5
    volumes:
      - ./shared:/shared
    ports:
      - 80:80
    env_file:
      - seafile.env
``` 
seafile.env looks like that:
```
SEAFILE_SERVER_HOSTNAME='seafile.domain.tld'
SEAFILE_ADMIN_EMAIL='admin@domain.tld'
SEAFILE_ADMIN_PASSWORD='megasecret'
```

The first launch is no problem. everthing is set up correctly (imho). 
now i clean up everything docker related:
```
docker rm $(docker ps -a -q)
```
When relaunching the compose with `docker-compose up` i get the following error:
```
 07:52:07  docker-compose up
Starting seafiledocker_seafile_1 ... done
Attaching to seafiledocker_seafile_1
seafile_1  | *** Running /etc/my_init.d/01_create_data_links.sh...
seafile_1  | ln: /opt/seafile/seahub-data: cannot overwrite directory
seafile_1  | *** /etc/my_init.d/01_create_data_links.sh failed with status 1
seafile_1  |
seafile_1  | *** Killing all processes...
seafiledocker_seafile_1 exited with code 1
```
launching it via `docker-compose up -V`works fine. 

=> there seems to be something strange with the docker volumes?

EDIT: this seems NOT to be reproducable:
1. initial setup
2. stop and remove container
3. start works not
4. start with -V works
5. start without -V works
6. stop and remove container
7. works without -V
8. restart without -V works NOT

quite confusing
