### ISSUE TITLE
HOWTO run garbage collection in the docker?

### ISSUE THREAD

**Issue by yatesco** [haiwen/seafile-docker#66]
I `bash`ed into the docker, stopped the server, ran `seaf-gc.sh --dry-run` and it went through some libraries but then terminated the docker.

Have I missed something?

**Comment by shoeper** [comment]
I think it exits because pid 1 exits. So instead you have to run bash in the container (docker run ... bash - stop the container before), Seafile shouldn't start and you should be able to run the GC. Directly running the GC instead of bash should also work.

**Comment by pbuyle** [comment]
What about?
`docker exec seafile /opt/seafile/seafile-server-latest/seafile.sh stop && docker exec seafile /opt/seafile/seafile-server-latest/seaf-gc.sh && docker exec seafile /opt/seafile/seafile-server-latest/seafile.sh start`
It seems to work on my server.

**Comment by yatesco** [comment]
Thanks @pbuyle - I just tried that but it still has the same effect, namely it will GC 3 or 4 libraries but then terminates.

**Comment by akomm** [comment]
you need to pass in the command via `bash -c` because of how the entry point is created and otherwise your command is appended.

I have created a simple script on the host machine which I can execute and it works:
```sh
#!/usr/bin/env bash

SF_BIN=/opt/seafile/seafile-server-latest

docker exec -it seafile bash -c "$SF_BIN/seafile.sh stop && $SF_BIN/seaf-gc.sh && $SF_BIN/seafile.sh start"
```

**Comment by yatesco** [comment]
Thanks @akomm - I ran that script but it still exited without processing all of the libraries and without restarting seafile.

I should mention I am using `docker-compose.yml` if that makes a difference?:
```
version: "2"
services:
  seafile:
    image: seafileltd/seafile:latest
    ports: 
      - 80:80
      - 443:443
    volumes:
      - /root/opt-seafile:/shared
    environment:
      - SEAFILE_SERVER_LETSENCRYPT=true
      - SEAFILE_SERVER_HOSTNAME=XXXXX
      - SEAFILE_ADMIN_EMAIL=XXXXX
      - SEAFILE_ADMIN_PASSWORD=XXXXX
```
