### ISSUE TITLE
Run the Seafile server with user other than root

### ISSUE THREAD

**Issue by fakuivan** [haiwen/seafile-docker#86]
To facilitate migration from the native environment where seafile ran as a regular user (other than root). The server can then run under UID of the user that owned the server files previously. 
I suppose this can also be taken advantage of by more paranoid users that don't like WWW services to be unnecessarily run as root, even on containers.

**Comment by languitar** [comment]
This is more or less a duplicate of #22, which isn't resolved at all. With a custom user specified via docker, start up fails with this exception:

```
Traceback (most recent call last):
  File "/sbin/my_init", line 414, in <module>
    main(args)
  File "/sbin/my_init", line 330, in main
    import_envvars(False, False)
  File "/sbin/my_init", line 90, in import_envvars
    for envfile in listdir("/etc/container_environment"):
  File "/sbin/my_init", line 74, in listdir
    return sorted(os.listdir(path))
PermissionError: [Errno 13] Permission denied: '/etc/container_environment'
```

**Comment by shoeper** [comment]
This is inherited from https://github.com/phusion/baseimage-docker/issues/264

Looks like my_init being used requires root privileges.  It should be configured to start Seafile as seafile, though.

**Comment by languitar** [comment]
I tried to implement this for a second, but somehow start up stopped at some point and then I gave up on this.

**Comment by fakuivan** [comment]
You don't need to run all processes as an unprivileged user, just the seafile components (the setup script, seahub.sh, seafile.sh, sf-gc.sh). Things like mariadb and nginx can run as root because they manage those privileges correctly and fork when needed. The seafile components are ment to be run as unprivileged.

**Comment by shoeper** [comment]
Maybe the easiest would be to add a seafile user and run start.py using su seafile -c "/scripts/start.py" https://github.com/haiwen/seafile-docker/blob/master/image/seafile/Dockerfile#L18

GC and so on could then be run using `docker exec -useafile -it seafile bash` (or directly without first entering the bourne-again shell) or using su seafile within the container.

Just changing this would lead to an issue though: existing setups would have broken permissions (and some paths need new permissions anyway to make this work). Fixing permissions on start could be an option but doing it naively would take quite some time for larger setups with millions of files.

The best would be if user scripts would also deny running them without using the seafile user within the docker container.

**Comment by fakuivan** [comment]
I don't think this should be enforced, but optional. UID and GID variables can be passed to the container intead of hardcoring one, if those are not set then the seafile components should be just run as root

**Comment by fakuivan** [comment]
This has not been resolved so don't close it

**Comment by Lordroran** [comment]
Is this possible with Seafile 7? This Issue is the only Thing blocking me from using Seafile on Docker.

**Comment by fakuivan** [comment]
@Lordroran I doubt it, the nginx server still runs on the container

**Comment by renfeipeng** [comment]
We think that the nginx direction proxy is a component we must rely on, it is necessary to put it in the same container.

**Comment by fakuivan** [comment]
@renfeipeng Why is this closed considering the previous comment?

**Comment by mishka81** [comment]
Problem is still present with seafile 7 image.

**Comment by techmunk** [comment]
I was able to get this to work with the following configuration:

docker-compose.yml
```yml
seafile:
    image: docker.seadrive.org/seafileltd/seafile-pro-mc:latest
    entrypoint: /usr/local/bin/entrypoint.sh
    volumes:
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
      - type: bind
        source: ./entrypoint.sh
        target: /usr/local/bin/entrypoint.sh
        read_only: true
      - type: bind
        source: ./gosu
        target: /usr/local/bin/gosu
        read_only: true
      - type: bind
        source: ./seafile
        target: /shared
        read_only: false
```

entrypoint.sh
```sh
#!/bin/bash

addgroup --gid 988 seafilegroup
useradd -s /bin/bash -u 1000 -m -d /home/seafileuser -g seafilegroup -k /dev/null seafileuser

chown seafileuser:seafilegroup /opt/seafile

sed -i 's!{} start!/usr/local/bin/gosu seafileuser:seafilegroup {} start!g' /scripts/start.py

/sbin/my_init -- /scripts/start.py
```

gosu was downloaded from https://github.com/tianon/gosu/releases

Update the uid and gid in the entrypoint.sh script as required. Don't forget to set the mounted "/shared/seafile" folder to be owned by the same uid:gid.

**Comment by lowne** [comment]
To improve upon @techmunk's excellent solution, it's possible to bake it into the image; among other things, this allows the container to be restarted without exploding:

`Dockerfile`:
```
FROM {{ hub_image }}
RUN apt-get update && apt-get -y -qq install gosu && rm -rf /var/lib/apt/lists/*
COPY imagesetup.sh /
RUN /imagesetup.sh && rm /imagesetup.sh
```

`imagesetup.sh`:
```
#!/bin/bash

# https://github.com/haiwen/seafile-docker/issues/86#issuecomment-573274807

GROUPNAME=$(getent group "{{ PGID }}" | cut -d ':' -f 1)

if [ -z $GROUPNAME ]
then
	addgroup --gid {{ PGID }} seafile
	GROUPNAME=seafile
fi

useradd -s /bin/bash -u {{ PUID }} -m -d /home/seafile -g $GROUPNAME -k /dev/null seafile
sed -i 's!{} start!/usr/sbin/gosu seafile:'$GROUPNAME' {} start!g' /scripts/start.py
chown seafile:$GROUPNAME /opt/seafile

# memcached host is hardcoded, gotta override
# sed -i 's!memcached:11211!{{ mc_svc_name }}:11211!g' /scripts/bootstrap.py
```
The last line is only relevant if you want/need to rename the memcached host in your setup.

**Comment by svengreb** [comment]
##### My experience

I've also tried to run the _Seafile_ server and _SeaHub_ as non-privileged user using a custom _Dockerfile_ similar to the one @lowne posted (using `RUN` statements instead of a separate script). It started without errors, at least after the 2nd container start because one needs to change the Linux filesystem ownership of the directories that have been created by the bootstrap script to the custom user (`seafile` in my case with UID/GID `5000:5000`).
Unfortunately the first problems occurred right after browsing to the login page was loaded without any CSS, JS and images. It was caused by a `403 Forbidden` HTTP status code to the `/media/*` path that is defined in the `nginx.conf` to point to `/opt/seafile/seafile-server-latest/seafile`. I tired multiple other ways to solve this, e.g. by allowing various security-related headers, [adding additional _Traefik_ routers][tr] and middleswares for the `/media/*` path, and some more. Even changing the ownership of the whole `/opt/seafile` and `/shared` paths to my custom user failed. Strangely enough the only workaround that worked was to remove the whole `location /media` block from `nginx.conf`, but that's definitely not what you want.

**Long story short**: I ended up running the _Seafile_ server as `root` for now until there's maybe official support for custom Docker users. Even if I had made it work without the strange workaround described above there are still other processes next to _Seafile_ itself that are running in the container as `root` like e.g. multiple ones from `nginx`. These are way harder to “fix“ since it is not possible to start a process as non-root user that binds to a port <1024 due to (absolute legitimate) Linux security policies. So finding a working way for Seafile to run as non-privileged is still not enough to run the container without `root` at all.

##### Optimal solution

Even though the [seafileltd/seafile-mc][img] _Docker_ image is a great improvement through the decoupling of the database and cache into their own containers, in my opinion the only way would be to split the stack even more by getting rid of running multiple processes in a single Docker container like e.g. `nginx`. Instead of relying on a proxy to route requests to the services, the internal structure needs to be refactored so every component can run in it's own container and requests are routed by components that have been designed for it (e.g. Docker Compose/Swarm ports, external routers like _Traefik_ or Kubernetes Ingresses). 

##### Better way to handle “hardcoded“ _memcached_ network name/alias

This is a bit unrelated to the main topic of this issues, but I thought it might help others that stumble across here.
@lowne posted a simple way to solve the problem of the “hardcoded“ network/alias name for the _memached_ component that is [defined in the `seahub_settings-py` file][ref]:

```
# sed -i 's!memcached:11211!{{ mc_svc_name }}:11211!g' /scripts/bootstrap.py
```

This “fix“ works when using a custom _Dockerfile_ but might be a blocker again for other who don't want or can do it and need another way.

I've tried to “fix“ this by simply following the [official Seafile documentations about how to add memcached][d], but for some reason the `CACHES` blog in the `seahub_settings.py` are not respected not even after deleting the `__pycache__` directory (Python is a terrible language 😣).
In the end I've solved this problem for my _Docker Compose_ setup by using a [network alias][dna] for my service that is named `seafile-cache` instead of `memcached`. Here's a stripped down example of how to use it:

```yml
version: "3.7"
services:
  seafile:
    image: seafileltd/seafile-mc:7.1.4
    networks:
      - seafile-net
    # ...

  seafile-db:
    image: mariadb:10.5.4
    networks:
      - seafile-net
    # ...

  seafile-cache:
    image: memcached:1.6.6
    networks:
      seafile-net:
        aliases:
          # Make this service available through the "memcached" alias.
          # This is required since the name is hardcoded in the SeaHub source code and configurations in
          # the "seahub_settings.py" are not respected.
          # See:
          #   - https://github.com/haiwen/seafile-docker/blob/55930f2/scripts/bootstrap.py#L154
          #   - https://docs.docker.com/compose/compose-file/#aliases
          - memcached
    # ...
```

This way my _memcached_ container is reachable for all other containers in the `seafile-net` netwotk through the `seafile-cache` and `memcached` name which make a change in the `scripts/bootstrap.py` file unnecessary. Using a network alias doesn't require to change actual source code and makes the setup compatible for changes in future versions.

[tr]: https://docs.traefik.io/routing/routers
[img]: https://hub.docker.com/r/seafileltd/seafile-mc
[dna]: https://docs.docker.com/compose/compose-file/#aliases
[ref]: https://github.com/haiwen/seafile-docker/blob/55930f2/scripts/bootstrap.py#L154
[d]: https://download.seafile.com/published/seafile-manual/deploy/add_memcached.md
