### ISSUE TITLE
latest image causes bad request

### ISSUE THREAD

**Issue by hasufell** [haiwen/seafile-docker#91]
```contradictory scheme handlers```

Doesn't happen with 6.2.5.

**Comment by falkzilm** [comment]
I have the same problem and trying to solve this. 
I think it has something to do with proxy settings and seafile docker settings, in my env i have a nginx proxy which delegates requests to docker images and maintain letsencrypt certs. 

I configured it to use always HTTPS for the outside so if i open the page in browser it will always be https. But internaly he delegates maybe with HTTP and i think this causes with HTTP/2.0 some problems - i am trying to find a way to solve this out..

**Comment by shoeper** [comment]
Have you checked the logs?
Execute bash within the container and check /var/log/nginx/* and /opt/seafile/logs/*

**Comment by yopbot** [comment]
I've checked both directories and no trace of the problem.

So far my solution is to comment "proxy_set_header X-Forwarded-Proto $scheme;" out in /templates/seafile.nginx.conf.template

**Comment by shoeper** [comment]
So the issue is obvious.

Your proxy sets `X-Forwarded-Proto https` and the nginx proxy within the image sets another one to `X-Forwarded-Proto  http`. Now you the two are contradictory.

**Comment by hasufell** [comment]
The issue may be obvious, but not the proper solution.

**Comment by mplorentz** [comment]
I am having the same issue, same setup. @yopbot's workaround fixes the issue for me. I'm happy to attempt a PR if we know what the fix should be.

**Comment by crystalnet** [comment]
+1
just ran into the same issue. a fix would be much appreciated 😃 👍 🙏

**Comment by realies** [comment]
it is still an issue

**Comment by orangelynx** [comment]
Also the bad request says "Contradictory scheme headers" (not handlers, at least for me, for people googling the issue).

In general the docker image leaves much to be desired, if anyone has an alternative option, I'd appreciate a pointer.

**Comment by windsource** [comment]
I use [sunx/seafile](https://hub.docker.com/r/sunx/seafile) with SQLite and an external nginx proxy. That works quite OK.

**Comment by melikyuksel** [comment]
Still no solution to this?

**Comment by Redsandro** [comment]
@renfeipeng did you close this in favor of #167? I would like to make two suggestions for future issues:

1. Close the newer issue as duplicate, not the older issue. Older issues already collected some knowledge and speculation, and rank higher in google search results.
2. Please comment why it was closed. When coming from google, users don't know about #167 and closing issues without a comment or addressing the issue does not inspire confidence in this otherwise wonderful project.

This is a legitimate issue. Many people use reverse proxies so they can host multiple services on a single VPS.

### Here is how I got seafile-docker 7.0.4 working with nginx-proxy:

Copy [`seafile.nginx.conf.template`](https://github.com/haiwen/seafile-docker/blob/master/templates/seafile.nginx.conf.template) to the directory where you `placed docker-compose.yml`.

Edit `seafile.nginx.conf.template`:

 ```diff
    server_name {{ domain }};

-    client_max_body_size 10m;
+    client_max_body_size 0;

    location / {
        proxy_pass http://127.0.0.1:8000/;
        proxy_read_timeout 310s;
        proxy_set_header Host $host;
-        proxy_set_header Forwarded "for=$remote_addr;proto=$scheme";
+        proxy_set_header Forwarded "for=$proxy_add_x_forwarded_for;proto=$http_x_forwarded_proto";
-        proxy_set_header X-Forwarded-For $remote_addr;
+        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
-        proxy_set_header X-Forwarded-Proto $scheme;
+        proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
-        proxy_set_header X-Real-IP $remote_addr;
+        proxy_set_header X-Real-IP $proxy_add_x_forwarded_for;
        proxy_set_header Connection "";
        proxy_http_version 1.1;
    }
```

(The change to `client_max_body_size` is necessary if you want to be able to sync files larger than 10 MB.)

Change your [`docker-compose.yml`](https://download.seafile.com/d/d7c8da31bf9f47db938e/files/?p=/docker/docker-compose.yml) like so:

```diff
  seafile:
    image: seafileltd/seafile-mc:latest
    container_name: seafile
-    ports:
-      - "80:80"
-#     - "443:443"  # If https is enabled, cancel the comment.
+  expose:
+    - 80
    volumes:
      - /opt/seafile-data:/shared   # Requested, specifies the path to Seafile data persistent store.
+     - ./seafile.nginx.conf.template:/templates/seafile.nginx.conf.template:ro
    environment:
+      VIRTUAL_HOST: seafile.example.test
+      VIRTUAL_PORT: 80
+      LETSENCRYPT_HOST: seafile.example.test
+      LETSENCRYPT_EMAIL: user@example.test
```

---

The minimal necessary steps to satisfy `nginx-proxy` users would be to change the headers in the nginx template. For illustrative purposes, I copy them from above:

```diff
-        proxy_set_header Forwarded "for=$remote_addr;proto=$scheme";
+        proxy_set_header Forwarded "for=$proxy_add_x_forwarded_for;proto=$http_x_forwarded_proto";
-        proxy_set_header X-Forwarded-For $remote_addr;
+        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
-        proxy_set_header X-Forwarded-Proto $scheme;
+        proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
-        proxy_set_header X-Real-IP $remote_addr;
+        proxy_set_header X-Real-IP $proxy_add_x_forwarded_for;
```

However, to make `seafile-docker` work _without_ nginx-proxy, someone simply needs to add some checks to the template:

```
if [the proxy headers exist]:
    use them
else:
    use current template values
```

This would satisfy all users. I think until this is written and tested, this issue should not be closed.

**Comment by renfeipeng** [comment]
Thank you for your suggestion, I think what you said is very reasonable.

**Comment by lcdtyph** [comment]
@Redsandro 
The nginx variable $proxy_add_x_forwarded_for won't be empty. If the xff header is not set by the reverse proxy, this var will be equal to $remote_addr. So the if is not needed.

BTW I think the X-Real-IP header should keep "real ip".

**Comment by Redsandro** [comment]
@lcdtyph 

> The nginx variable $proxy_add_x_forwarded_for won't be empty. If the xff header is not set by the reverse proxy, this var will be equal to $remote_addr. So the if is not needed.

Great! :+1: 

> BTW I think the X-Real-IP header should keep "real ip".

I'm not sure what you mean. The X-Real-IP should be the real internet-facing customer IP. So we need an `if`, right?

If (X-Real-IP exists): Keep X-Real-IP
else: Use $remote_addr.

In my example I'm using $proxy_add_x_forwarded_for because it will always be the final ip address (in case of maximum 1 proxy, which is the case with nginx-proxy)

**Comment by cr1st1p** [comment]
I just added a pull request to improve the docker image #187, one fix being using it behind a SSL termination proxy (I'm using it inside a kubernetes cluster)

Suggestions:
a) for seafile behind an nginx as SSL termination proxy, like @falkzilm  seem to have, with that PR, you would set environment variable BEHIND_SSL_TERMINATION and it will automatically set 'proto' to ssl and not $scheme
b) at first look, to me it looks like the nginx template and associated code should handle a new environment variable to let it know it is behind a proxy and instead of using 
```proxy_set_header X-Forwarded-For $remote_addr;`` 
it would use
```proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;```
  Also, having BEHIND_SSL_TERMINATION enabled should automatically enable it.

  Update: Looking at an nginx ingress controller setup I see more interesting stuff that could make it into the image + maybe different method of defining the nginx configuration lines.
  I might try an update on the nginx config, but only if effort is worthwhile - that is, the mentioned pull request gets accepted.

**Comment by patrick-birkle** [comment]
Unfortunately I'm not able setting up seafile behind my nginx reverse proxy (nginx, jwilder/docker-gen and jrcs/letsencrypt-nginx-proxy-companion). Neither the workaround from @shoeper nor the workaround from @Redsandro are working for me. 

Does anyone know if this repository is still maintained and if there are any plans in fixing the problem?

**Comment by cr1st1p** [comment]
@patrick-birkle I updated today my PR, added info on the environment variables used and also created a docker image at https://hub.docker.com/repository/docker/cr1st1p/seafile-server
You did not provide details about what is not working for you, but try that image. And I think you need to set BEHIND_SSL_TERMINATION=1

**Comment by saimonsez** [comment]
@Redsandro: Your comment helped me to make seafiles web-ui accessible behind an nginx-proxy. Thank you very much! However, clients are still unable to sync, I guess thats because of fastcgi. Will this be solved with your PR and do you have a workaround in the meantime?

What I can see in nginx-proxy logs is

```
[01/Mar/2020:12:07:16` +0000] "GET /seafhttp/protocol-version HTTP/1.1" 503 197 "-" "Seafile/7.0.4 (Windows NT)"
```
and nothing in seafile logs.

Clients display "waiting for sync" with a grey icon.

**Comment by Redsandro** [comment]
@saimonsez I'm not sure why it doesn't work for you. The clients connect over the same port, right? The web-ui address is the same address you enter into the client when connecting, right?

If the client connection doesn't work, but the web-ui connection _does_ work, then I'm not sure why this is. Are you connecting to a different url?

Seafile did change from version 6 to 7 in the meantime. I'll post my updated files in case it helps you:

### `docker-compose.yml`

Notice how the only port exposed is port 80. The nginx-proxy uses that internally to provide the TLS.

```
version: '3.5'

volumes:
    seaf-shared:
    seaf-db:

networks:
    seaf-net:
    nginx-proxy:
        external:
            name: nginx-proxy

services:
  db:
    image: mariadb:10.1
    container_name: seaf-db
    restart: always
    env_file:
      - seaf-db.env
    volumes:
      - seaf-db:/var/lib/mysql
    networks:
      - seaf-net

  memcached:
    image: memcached:1.5.6
    container_name: seaf-memcached
    restart: always
    entrypoint: memcached -m 256
    networks:
      - seaf-net

  seafile:
    image: seafileltd/seafile-mc:latest
    container_name: seaf-mc
    restart: always
    expose:
      - 80
    volumes:
      - seaf-shared:/shared
      - ./seafile.nginx.conf.template:/templates/seafile.nginx.conf.template:ro
    env_file:
      - seaf.env
    environment:
      DB_HOST: db
      VIRTUAL_HOST: [my-reverse-proxy-domain]
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: [my-reverse-proxy-domain]
      LETSENCRYPT_EMAIL: [my-email-address]
    links:
      - db
      - memcached
    networks:
      - nginx-proxy
      - seaf-net
```

### `seafile.nginx.conf.template`

```
# -*- mode: nginx -*-
# Auto generated at {{ current_timestr }}
{% if https -%}
server {
    listen 80;
    server_name _ default_server;
    rewrite ^ https://{{ domain }}$request_uri? permanent;
}
{% endif -%}

server {
{% if https -%}
    listen 443;
    ssl on;
    ssl_certificate      /shared/ssl/{{ domain }}.crt;
    ssl_certificate_key  /shared/ssl/{{ domain }}.key;

    ssl_ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+3DES:!aNULL:!MD5:!DSS;

    # TODO: More SSL security hardening: ssl_session_tickets & ssl_dhparam
    # ssl_session_tickets on;
    # ssl_session_ticket_key /etc/nginx/sessionticket.key;
    # ssl_session_cache shared:SSL:10m;
    # ssl_session_timeout 10m;
{% else -%}
    listen 80;
{% endif -%}

    server_name {{ domain }};

    client_max_body_size 0;

    location / {
        proxy_pass http://127.0.0.1:8000/;
        proxy_read_timeout 310s;
        proxy_set_header Host $host;
        proxy_set_header Forwarded "for=$proxy_add_x_forwarded_for;proto=$http_x_forwarded_proto";
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
        proxy_set_header X-Real-IP $proxy_add_x_forwarded_for;
    }

    location /seafhttp {
        rewrite ^/seafhttp(.*)$ $1 break;
        proxy_pass http://127.0.0.1:8082;
        client_max_body_size 0;
        proxy_connect_timeout  36000s;
        proxy_read_timeout  36000s;
    }

    location /seafdav {
        client_max_body_size 0;
        fastcgi_pass    127.0.0.1:8080;
        fastcgi_param   SCRIPT_FILENAME     $document_root$fastcgi_script_name;
        fastcgi_param   PATH_INFO           $fastcgi_script_name;

        fastcgi_param   SERVER_PROTOCOL     $server_protocol;
        fastcgi_param   QUERY_STRING        $query_string;
        fastcgi_param   REQUEST_METHOD      $request_method;
        fastcgi_param   CONTENT_TYPE        $content_type;
        fastcgi_param   CONTENT_LENGTH      $content_length;
        fastcgi_param   SERVER_ADDR         $server_addr;
        fastcgi_param   SERVER_PORT         $server_port;
        fastcgi_param   SERVER_NAME         $server_name;

        access_log      /var/log/nginx/seafdav.access.log;
        error_log       /var/log/nginx/seafdav.error.log;
    }

    location /media {
        root /opt/seafile/seafile-server-latest/seahub;
    }

    # For letsencrypt
    location /.well-known/acme-challenge/ {
        alias /var/www/challenges/;
        try_files $uri =404;
    }
}
```

**Comment by saimonsez** [comment]
@Redsandro, thanks for the update.

I adopted your seafile.nginx.conf.template and my docker-compose.yml is

```
version: '2.0'
services:
  db:
    image: mariadb:10.1
    container_name: seafile-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
    volumes:
      - .db:/var/lib/mysql

  memcached:
    image: memcached:1.5.6
    container_name: seafile-memcached
    entrypoint: memcached -m 256

  seafile:
    image: seafileltd/seafile-mc:latest
    container_name: seafile
    expose:
      - 80
    volumes:
      - ./data:/shared
      - ./seafile.nginx.conf.template:/templates/seafile.nginx.conf.template:ro
    environment:
      - DB_HOST=db
      - DB_ROOT_PASSWD=
      - TIME_ZONE=Europe/Zurich
      - SEAFILE_ADMIN_EMAIL=
      - SEAFILE_ADMIN_PASSWORD=
      - VIRTUAL_HOST=seafile.domain.com
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=seafile.domain.com
      - LETSENCRYPT_EMAIL=email@domain.com
    depends_on:
      - db
      - memcached
networks:
  default:
    external:
      name: nginx-proxy
```
and docker-compose.yml of nginx-proxy

```
version: '2'

services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf:/etc/nginx/conf.d
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./dhparam:/etc/nginx/dhparam
      - ./certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-le
    depends_on:
      - nginx-proxy
    volumes_from:
      - nginx-proxy
    volumes:
      - ./certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always

networks:
  default:
    external:
      name: nginx-proxy
```
Thats not exaclty as yours but should fit. Still, clients can not sync.

Do you use any other env variables or special nginx config of jwilder/proxy?
